config/routes.rb
Dreallow::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users do
    get "likes", to: "users#likes"
  end

  get "dream/random", to: "dreams#random"
  resources :dreams do

    member do
      put "like", to: "dreams#upvote"
      get "like", to: "dreams#upvote"
    end
    resources :comments
    resources :meanings do
      resources :comments
    end
  end

  root :to => "pages#landing"

end

app/models/dream.rb
# == Schema Information
#
# Table name: dreams
#
#  id         :integer          not null, primary key
#  content    :text(255)
#  user_id    :integer
#  shared     :boolean          default(TRUE)
#  created_at :datetime
#  updated_at :datetime
#

class Dream < ActiveRecord::Base
  has_many :comments, as: :commentable
  belongs_to :user
  has_many :meanings

  validates :content, presence: true

  acts_as_votable

  default_scope order: 'dreams.created_at DESC'
end

app/controllers/dreams_controller.rb
class DreamsController < ApplicationController

  def index
    @dreams = Dream.all
  end

  def new
    @dream = current_user.dreams.build
  end

  def show
    @dream = Dream.find(params[:id])
    @meanings = @dream.meanings
    @comments = @dream.comments
  end

  def create
    if current_user
      @dream = current_user.dreams.build(dream_params)
    else
      @dream = Dream.new(dream_params)
    end
    if @dream.save
      if current_user.present?
        redirect_to dreams_path, flash: { notice: "Dream successfully created" }
      else
        redirect_to root_path
      end
    else
      render "new"
    end
  end

  def destroy
    Dream.find(params[:id]).destroy
    redirect_to dreams_path, flash: { notice: "Dream successfully deleted" }
  end

  def upvote
    @dream = Dream.find(params[:id])
    @dream.liked_by current_user
    redirect_to dream_path(@dream)
  end

  def random
    @dream = Dream.first(:order => "RANDOM()")
    redirect_to dream_path(@dream)
  end

  private
  def dream_params
    params.require(:dream).permit(:content, :shared)
  end
end

app/helpers/dreams_helper.rb
module DreamsHelper
end

app/views/dreams/_dream.html.erb
<div class="circContent">
  <span>
    <%= truncate(dream.content, length: 80)%>
  </span> 
</div>

app/views/dreams/_form.html.erb
<%= form_for(dream) do |f| %>
    <%= f.text_area :content, :placeholder => "Share your dreams..." %>
    <% if current_user %>
      <div class="sharedBool">
        <%= f.label "Public dream" %>
        <%= f.check_box(:shared) %>
      </div>
    <% end %>
    <%= f.submit "submit", class: "btn btn-small" %>
<% end %>

app/views/dreams/index.html.erb
<div class="wrapper">
  <div class="enter_dream" >
    <%=  render '/dreams/form', dream: Dream.new %>
  </div>
  <div class="clearfix listOfDreams">
    <% @dreams.each do |dreame| %>
      <% if dreame.shared %>
      <%= link_to dream_path(Dream.find(dreame.id)) do %>
      <div class="circle">
      <div class="circContent">
        <%= render "dream", dream: dreame %>
      </div>
      <div class="userAndLoc">
        <%= time_ago_in_words(dreame.created_at) %> <br />
        <% if dreame.user %>
          <strong><%= dreame.user.name.split(' ')[0] << " " << dreame.user.name.split(' ')[1] %>, 
          <%= dreame.user.location.split(',').join.split(' ')[0]   %></strong>
      <% else %>
          <strong><%=  "Anonymous, Anonymous" %></strong>
      <% end %>
        <span>
          <%= link_to "Like", like_dream_path(dreame, method: :put) %>
        </span>
        <% if (current_user == dreame.user) %>
          <span>
          <%= link_to "delete", dreame, method: :delete, data: {confirm: "Are you sure?"} %>
        </span>
      <% end %>
      </div>
    </div>
  <% end %>
  <% end %>
  <% end %>
  </div>
</div>

app/views/dreams/new.html.erb
<%= link_to (image_tag('Dreallow_FBcover.jpg')), root_path, class: "brand"  %>
<%= render "form", dream: @dream %>

app/views/dreams/show.html.erb
<div id="wrap">
  <div id="header">
    <%= image_tag("Dreallow_cover.jpg", alt: "FB cover", width: 813) %>
  </div>
  <div id="content">
    <h2 center>What did you just dream?    </h2>

    <%= @dream.content %>
    <div id="js-meanings">
      <% if current_user %>
        <%= link_to "Add Meaning", [:new, @dream, :meaning], id: "js-new-meaning-link", remote: true %>
    <% end %>
      <%= render @meanings %>
    </div>

    <div id="js-comments">
      <% if current_user %>
        <%= link_to "Add Comment", [:new, @dream, :comment], id: "js-new-comment-link", remote: true %>
    <% end %>
      <%= render @comments %>
    </div>


    <div id="divider"></div>

    <div id="bottom">

      <div id="bottomleft"></div>

      <div id="footer">Join the team for more fun on <a href="http://www.facebook.com/dreallow">Facebook | Dreallow</a><a href="#"></a>. </div>

    </div>
  </div>

</div>

app/views/dreams/show.js.erb
$('#js-meanings').append('<%= j render(@meanings, dream: @dream) %>');