config/routes.rb
Dreallow::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :users do
    get "likes", to: "users#likes"
  end

  get "dream/random", to: "dreams#random"
  resources :dreams do

    member do
      put "like", to: "dreams#upvote"
      get "like", to: "dreams#upvote"
    end
    resources :comments
    resources :meanings do
      resources :comments
    end
  end

  root :to => "pages#landing"

end

app/views/pages/landing.html.erb
<div class="main">
  <section class="page1">
    <div class="page_container">
      <div class="logo_container">
        <%= image_tag "logo.png", class:"logo" %>
        <h2 class="slogan">Share your dreamzZz...</h2>
      </div>
      <div class="btns">
        <form class="">
          <fieldset class="login">
            <legend>The dream realm is nigh</legend>
            <%= link_to user_omniauth_authorize_path(:facebook),  class: "btn btn-info btn-large loginbtn" do %>
              Sign in with <strong>[Facebook]</strong>
          <% end %>
          </fieldset>
        </form>
      </div><!-- btns -->
      <div class="dream_enter">
        <%=  render '/dreams/form', dream: Dream.new %>
      </div>
    </div><!--page container -->
  </section>
  <div class="clouds">
    <div class="cloud-1" data-speed="35000"></div>
    <div class="cloud-2" data-speed="45000" data-delay="15000"></div>
    <div class="cloud-3" data-speed="40000"></div>
    <div class="cloud-4" data-speed="38000" data-delay="20000"></div>
  </div>
  <section id="dreams" class="page2">
    <div class="page_container">
      <div class="wrapper">
        <h2>See what people are dreaming right this moment</h2>
        <% @trending.each do |trend| %>
          <%= link_to dream_path(Dream.find(trend.id)) do %>
          <div class="circle">
          <div class="circContent">
            <%= truncate(trend.content, length: 80) %> <br />
          </div>
        <% end %>
          <div class="userAndLoc">
            <%= time_ago_in_words(trend.created_at) %> <br />
            <% if trend.user %>
              <!--<strong><%= trend.user.name.split(' ')[0] + " " + trend.user.name.split(' ')[1] %>, <%= trend.user.location.split(',').join.split(' ')[0]%></strong>-->
          <% else %>
              <strong><%=  "Anonymous, Anonymous" %></strong>
          <% end %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </section>
</div><!--main -->
<footer>
  <a class="back" href="http://www.facebook.com/dreallow">Team Dreallow</a>
</footer>